spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/rest_api_spring_boot?useTimezone=true&serverTimezone=UTC
      username: root
      password: urubu100
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false






#server.port=8080
#
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/ms_email
#spring.datasource.username=root
#spring.datasource.password=urubu100
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
##spring.jpa.show-sql: true
